name: Update POD Market Content

on:
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Trigger deployment
        run: |
          # Create a small change to trigger the main deployment
          echo "# Last updated: $(date -u)" > .last-update
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .last-update
          git commit -m "chore: trigger daily content update [skip ci]" || exit 0
          git push

      - name: Comment on latest issue
        uses: actions/github-script@v7
        with:
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 1
            });
            
            if (issues.length > 0) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issues[0].number,
                body: `🔄 **Daily Content Update**\n\nContent has been refreshed with latest POD market updates from RSS feeds.\n\n- **Time**: ${new Date().toISOString()}\n- **Source**: Automated RSS feed aggregation\n- **Next Update**: Tomorrow at 9 AM UTC`
              });
            }
