name: Update POD Market Content

on:
  schedule:
    # Run every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (prod only)
        run: |
          npm ci --omit=dev || npm ci

      - name: Build updates.json from RSS
        run: |
          node --version
          node scripts/fetch-updates.mjs

      - name: Install dependencies
        run: npm ci

      - name: Trigger deployment
        run: |
          # Create a small change to trigger the main deployment
          echo "# Last updated: $(date -u)" > .last-update
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/updates.json || true
          git add .last-update
          git status
          git commit -m "chore: trigger 2-hourly content update [skip ci]" || echo "No changes to commit"
          git push origin main || echo "Push failed, but continuing"

      - name: Comment on latest issue
        uses: actions/github-script@v7
        with:
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 1
            });
            
            if (issues.length > 0) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issues[0].number,
                body: `🔄 **2-Hourly Content Update**\n\nContent has been refreshed with latest POD market updates from RSS feeds.\n\n- **Time**: ${new Date().toISOString()}\n- **Source**: Automated RSS feed aggregation\n- **Next Update**: In 2 hours`
              });
            }
